"""Public API for compiling CVE metadata into a grounded PatchSpec v1."""

from .core import (
    PROMPT_VERSION,
    SCHEMA_VERSION,
    PatchSpecError,
    PatchSpecMetadataError,
    PatchSpecValidationError,
    assert_valid_patch_spec,
    build_anchors,
    build_deterministic_skeleton,
    build_hunks,
    canonical_json,
    eligible_indicator_refs,
    load_patch_spec_schema,
    metadata_sha256,
    model_input_view,
    patch_spec_cache_key,
    patch_spec_digest,
    prepare_metadata,
    prompt_view,
    resolve_json_pointer,
    resolve_source_excerpts,
    validate_patch_spec,
)
from .generator import PatchSpecModelConfig, PatchSpecResult, generate_patch_spec
from .storage import ensure_patch_spec, load_patch_spec, patch_spec_cache_path, write_patch_spec


__all__ = [
    "PROMPT_VERSION",
    "SCHEMA_VERSION",
    "PatchSpecError",
    "PatchSpecMetadataError",
    "PatchSpecModelConfig",
    "PatchSpecResult",
    "PatchSpecValidationError",
    "assert_valid_patch_spec",
    "build_anchors",
    "build_deterministic_skeleton",
    "build_hunks",
    "canonical_json",
    "eligible_indicator_refs",
    "ensure_patch_spec",
    "generate_patch_spec",
    "load_patch_spec",
    "load_patch_spec_schema",
    "metadata_sha256",
    "model_input_view",
    "patch_spec_cache_key",
    "patch_spec_cache_path",
    "patch_spec_digest",
    "prepare_metadata",
    "prompt_view",
    "resolve_json_pointer",
    "resolve_source_excerpts",
    "validate_patch_spec",
    "write_patch_spec",
]
